name: Trigger Workflow in selenium_docker

on:
  push:
    branches:
      - master  # Replace with the branch you want to trigger the workflow on
  workflow_dispatch: # Enable manual triggering of the workflow

jobs:
  trigger_Selenium_docker_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Selenium_docker Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.SELENIUM_DOCKER_PAT }}  # Replace with your personal access token for repo2
          repository: smitpatel01/Selenium_Docker  # Replace with your GitHub username and the name of repo2
          event-type: build_and_push  # Replace with the event type that matches your workflow_dispatch inputs in main.yml
          client-payload: '{}'  # You can pass additional data as JSON here if needed
